version: "2.1"
volumes:
  elasticsearch:
  postgres:
  redis:
  minio:
  web-node_modules:
  bots-node_modules:
services:
  elasticsearch:
    build: alegre/elasticsearch
    environment:
      - "discovery.type=single-node"
      - "transport.host=127.0.0.1"
      - "xpack.security.enabled=false"
      - "ALEGRE_URL=http://alegre:5000"
      - "cluster.name=docker-cluster"
      - "bootstrap.memory_lock=true"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m -Dlog4j2.disable.jmx=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - "./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
      - "elasticsearch:/usr/share/elasticsearch/data"
  postgres:
    image: postgres:9.5
    command: postgres -c config_file=/etc/postgresql.conf
    ports:
      - "5432:5432"
    volumes:
      - "./postgresql.conf:/etc/postgresql.conf"
      - "postgres:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: postgres
  redis:
    image: redis:5
    ports:
      - "6379:6379"
    volumes:
      - "redis:/data"
  minio:
    image: minio/minio
    command: server /data
    ports:
      - "9000:9000"
    volumes:
      - "minio:/data"
    environment:
      MINIO_ACCESS_KEY: AKIAIOSFODNN7EXAMPLE
      MINIO_SECRET_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
  api:
    build: check-api
    ports:
      - "3000:3000"
      - "3300:3300"
    depends_on:
      - elasticsearch
      - postgres
      - redis
      - pender
      - alegre
    volumes:
      - "./check-api:/app"
    environment:
      RAILS_ENV: development
      SERVER_PORT: 3000
  api-background:
    build: check-api
    command: /app/docker-background.sh
    depends_on:
      - api
    volumes:
      - "./check-api:/app"
    environment:
      RAILS_ENV: development
      SERVER_PORT: 3000
  pender:
    build: pender
    shm_size: 1G
    ports:
      - "3200:3200"
      - "9555:9555"
    volumes:
      - "./pender:/app"
    depends_on:
      - redis
      - minio
    environment:
      RAILS_ENV: development
      SERVER_PORT: 3200
  pender-background:
    build: pender
    command: /app/docker-background.sh
    shm_size: 1G
    volumes:
      - "./pender:/app"
    depends_on:
      - pender
    environment:
      RAILS_ENV: development
      SERVER_PORT: 3200
  web:
    build: check-web
    ports:
      - "3333:3333"
    depends_on:
      - api
    volumes:
      - "./check-web:/app"
      - "./check-api:/api"
      - "web-node_modules:/app/node_modules"
    environment:
      PLATFORM: web
      NODE_ENV: development
      SERVER_PORT: 3333
      MODE: development
  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.0
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
  alegre:
    build: alegre
    ports:
      - "3100:3100"
    volumes:
      - "./alegre:/app"
    depends_on:
      - kibana
      - redis
    environment:
      BOILERPLATE_ENV: dev
      ALEGRE_PORT: 3100
      REDIS_DATABASE: 2
  bots:
    build: check-bots
    volumes:
      - "./check-bots:/app"
      - "bots-node_modules:/app/node_modules"
    ports:
      - "8586:8586"
    depends_on:
      - api
    environment:
      NODE_ENV: development
      SERVER_PORT: 8586
